### ISSUE TITLE
Devils Preview Requires Stack

### ISSUE THREAD

**Issue by lacan** [BIOP/ijp-DEVILS#4]
Devils could be run on a very large single plane image
```
[ERROR] Module threw exception
java.lang.IllegalArgumentException: Stack required
	at ij.plugin.HyperStackConverter.toHyperStack(HyperStackConverter.java:59)
	at ij.plugin.HyperStackConverter.toHyperStack(HyperStackConverter.java:34)
	at ch.epfl.biop.lazyprocessing.LazyImagePlusHelper.create(LazyImagePlusHelper.java:23)
	at ch.epfl.biop.preview.DevilsInteractiveCommand.run(DevilsInteractiveCommand.java:80)
	at org.scijava.command.InteractiveCommand.preview(InteractiveCommand.java:95)
	at org.scijava.widget.AbstractInputHarvester.buildPanel(AbstractInputHarvester.java:91)
	at org.scijava.widget.InputHarvester.harvest(InputHarvester.java:67)
	at org.scijava.ui.AbstractInputHarvesterPlugin.process(AbstractInputHarvesterPlugin.java:74)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:154)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lacan** [comment]
I tested it on a single plane image, sorry. Just one channel one Z one T

**Comment by NicoKiaru** [comment]
Fixed in https://github.com/BIOP/ijp-DEVILS/commit/9ed388138f34b4af1e9206688538a279baf82412, but the image is opened and closed - it's not the best for the ui

**Comment by lacan** [comment]
Thanks boss man
